import json
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from pathlib import Path
from scipy.signal import gaussian, square
from warnings import warn
from qutip import *
import matplotlib.cm as cm



def show_amp_dispersive(amp_json, amp, sq, n_p):
    """
    Show transition amplitudes from new JSON files generated by main_const_pulse_multi_piece.cpp.
    Expects format: [pulse][qubit][time][cavity] with {"real": ..., "imag": ...}
    """
    import os

    if not amp_json:
        warn("No amplitude JSON files provided.")
        return
    if not Path(amp_json).is_file():
        warn(f"File {amp_json} does not exist.")
        return

    with open(amp_json, 'r') as f:
        data = json.load(f)

    # num_pulses = len(data)
    num_qubit = len(data)
    num_cavity = len(data[0])
    # print(f"num_pulses: {num_pulses}, num_qubit: {num_qubit}, num_cavity: {num_cavity}")
    print(f"num_qubit: {num_qubit}, num_cavity: {num_cavity}")

    dir_path = f"orig_plots/a{amp}_num_p{n_p}_nc{num_cavity}_nq{sq}"
    os.makedirs(dir_path, exist_ok=True)

    print(f"Loaded amplitude data from {amp_json}")
    
    # For each qubit, collect amplitudes over all pulses and times
    all_transition_amplitudes = []
    # for cavity_row in data:
    #     all_transition_amplitudes.append(complex(cavity['real'], cavity['imag']))
    #     all_transition_amplitudes.append(cavity_row)

    all_transition_amplitudes = [[complex(d['real'], d['imag']) for d in sub_data] for sub_data in data]
    # for pulse in data:
    #     print(f"pulse: {pulse}")
    #     cavity_row = []
    #     for cavity in pulse[0]:
    #         print(pulse[0])
    #         cavity_row.append(complex(cavity['real'], cavity['imag']))
    #     all_transition_amplitudes.append(cavity_row)

    nc = num_cavity
    psi_t = []
    for cn_t in all_transition_amplitudes:
        psi = basis(nc, 0)*0
        for n, cn in enumerate(cn_t):
            psi += cn*basis(nc, n)
        psi_t.append(psi)

    a = destroy(nc)
    alpha_t = expect(a, psi_t)

    # Plot the results
    plt.figure(figsize=(10, 6))
    plt.plot(alpha_t.real, alpha_t.imag, label=f'Qubit {sq}')
    plt.xlabel("Re(alpha_t)")
    plt.ylabel("Im(alpha_t)")
    plt.title(f"Cavity Amplitude Phase Space Trajectory (Qubit {sq})")
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(dir_path, f"phase_space_qubit_{sq}.png"))
    plt.show()


    times = np.arange(len(alpha_t))
    plt.figure(figsize=(10, 6))

    # color map based on time index
    plt.scatter(alpha_t.real, alpha_t.imag, c=times, cmap=cm.plasma, s=20)
    plt.plot(alpha_t.real, alpha_t.imag, color='gray', alpha=0.5)

    plt.xlabel("Re(alpha_t)")
    plt.ylabel("Im(alpha_t)")
    plt.title(f"Cavity Amplitude Phase Space Trajectory (Qubit {sq})")
    cbar = plt.colorbar(label="Time index")
    plt.grid(True)
    plt.savefig(os.path.join(dir_path, f"phase_space_qubit_{sq}_timeline.png"))
    plt.show()

def generate_amp_json(prefix, state, num_pulses, amp, q, n):
    """
    Generate filenames for amplitudes JSON files.
    Example: amplitudes_e_chg_pulse0amp0.025000_q18_n8_p192.json
    """
    return f"{prefix}_{state}_chg_amp{amp:.6f}_q{q}_n{n}_p{num_pulses}.json"
    # return f"{prefix}_{state}_chg_pulse{num_pulses}_amp{amp:.6f}_q{q}_n{n}.json"
    # return f"{prefix}_{state}_chg_amp{amp:.6f}_q{q}_n{n}.json"
    # return f"{prefix}_{state}_chg_amp{amp:.6f}_q{q}.json"


num_pulses = 64
amp = 0.002
q = 18
n = 10
# folder = "orig_revamped_results/amplitudes"
folder = "new_runs/amplitudes"

amp_json = generate_amp_json(folder, "e", num_pulses, amp, q, n)
show_amp_dispersive(amp_json,amp , 0, num_pulses)
amp_json = generate_amp_json(folder, "g", num_pulses, amp, q, n)
show_amp_dispersive(amp_json,amp , 1, num_pulses)
# print(amp_json)




